#!/bin/bash
# Do not run this directly!  Rather, any code you want to run on control AND worker nodes
# can be added here, as it runs before the cluster is initialized or before the worker joins.

if [[ $(whoami) = "root" ]]; then
   echo "Must not run as root."
   exit 1
fi

if [[ $SSD = '' ]]; then
   echo "Do not run this directly.  This is used by other scripts."
   exit 1;
fi

# Get onto a K8s and Docker version that will play nice together.
if command kubelet 2>/dev/null; then
   sudo systemctl stop kubelet
fi
if command docker 2>/dev/null; then
   sudo systemctl stop docker
fi
sudo apt-mark unhold kubelet kubeadm kubectl
sudo apt-get purge -y kubelet kubeadm kubectl
sudo apt-get update >/dev/null 2>&1
sudo apt-get remove -y docker docker-engine docker.io containerd runc
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common gnupg2 nfs-common open-iscsi
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update 
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo mkdir /etc/docker
sudo tee /etc/docker/daemon.json <<EOF >/dev/null
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
sudo mkdir -p /etc/systemd/system/docker.service.d

# Make sure $DATAFOLDER exists
sudo mkdir -p "$DATAFOLDER"
sudo mkdir -p "$DATAFOLDER"/docker
sudo mkdir -p "$DATAFOLDER"/etcd
sudo ln -s "$DATAFOLDER"/etcd /var/lib/etcd

# If there's a device at $SSD, we set it up to mount at the DATAFOLDER location.
if [[ -b "$SSD" ]]; then
   SSDUUID=$(lsblk "$SSD" -o UUID -n | tr '\n' ' ' | cut -c 2-37)
   echo "Found $SSD as $SSDUUID"

   if grep -q "$SSDUUID" /etc/fstab; then
      echo "Disk is already in /etc/fstab."
   else
      echo "UUID=$SSDUUID  $DATAFOLDER  ext4  defaults  0  2" | sudo tee -a /etc/fstab >/dev/null
      echo "Added $SSD to /etc/fstab"
   fi
   sudo mount "$DATAFOLDER"
fi

# Make sure that $DATAFOLDER/docker is where things are stored rather than /var/lib/docker 
SEDCMD="sed -i 's%^ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock.*$%ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -g $DATAFOLDER/docker%g' /lib/systemd/system/docker.service"
echo "Adding $DATAFOLDER to docker working folder"
eval "sudo $SEDCMD"

# if there is a way to resolve the $CONTROLPLANEENDPOINT to an ip address, do nothing.  It means /etc/hosts is already 
# configured or it's a FQDN or something.  Fine.  If not, set an IP address as the target of whatever the string is so
# resolve it.
RESOLVEDCONTROLIP=$(dig +short "$CONTROLPLANEENDPOINT")
if [[ ! -z "$RESOLVEDCONTROLIP" ]]; then
   echo "$CONTROLPLANEENDPOINT resolves to $RESOLVEDCONTROLIP already"
else
   echo "$CONTROLNODEIP $CONTROLPLANEENDPOINT" | sudo tee -a /etc/hosts >/dev/null
   echo "Added $CONTROLNODEIP $CONTROLPLANEENDPOINT entry to /etc/hosts"
fi

# Performance improves if you disable Transparent Huge Pages.
sudo apt-get install -y libhugetlbfs-bin
sudo tee /etc/rc.local <<EOF >/dev/null
#!/bin/bash
hugeadm --thp-never
EOF
sudo chmod a+x /etc/rc.local
sudo hugeadm --thp-never

# Swapfile must be off to run k8s properly
sudo swapoff -a >/dev/null 2>&1 || true
sudo sed -i '/^\/swap/s/^/#/' /etc/fstab

# Configure prerequisites for Kubernetes
sudo modprobe overlay
sudo modprobe br_netfilter
sudo tee /etc/sysctl.d/k8s.conf <<EOF >/dev/null
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
sudo sysctl --system

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo tee /etc/apt/sources.list.d/kubernetes.list <<EOF >/dev/null
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

# Check current versions available of these packages like this: apt-cache madison kubelet 
sudo apt-get update
sudo apt-get install -y kubelet=$KUBERNETESVERSION-00 kubeadm=$KUBERNETESVERSION-00 kubectl=$KUBERNETESVERSION-00
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl enable --now docker
# sudo systemctl enable --now kubelet

# Add tab completion to bash for kubectl
kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl >/dev/null
