#!/bin/bash

if [[ $(whoami) = "root" ]]; then
   echo "Must not run as root."
   exit 1
fi

source ./k8smaker_config

if [[ $1 = '' ]]; then
   echo "Pass IP or hostname of the new control-plane node as the first argument:"
   echo "./k8smaker_addcontrolplane_baremetal control2.local"
   exit 1
fi

mkdir -p ~/"$CLUSTERNAME"
ADDSCRIPT=~/"$CLUSTERNAME/k8smaker_addcontrolplane_$1"
KUBEADMSCRIPT=~/"$CLUSTERNAME/k8smaker_addcontrolplane_$1_join.yaml"

# this picks up your external facing IP address and hostname
NEWNODEIP=$(host $1 | tail -1 | awk '{ print $4 }')
echo "New control-plane node is $SSHUSERNAME@$1 at IP $NEWNODEIP"
echo "Script stored in $ADDSCRIPT"

# Delete an existing k8s install while leaving Docker alone.  Doesn't get rid of all the extra things we did, but those aren't harmful to reinstalling.
echo "You have 5 seconds before this script remotely deletes all Kubernetes and Etcd data.  Control-C To Abort!"
sleep 5

# configure us to be able to login remotely without a password
ssh-copy-id -f -i "$HOME/.ssh/$CLUSTERNAME.pub" "$SSHUSERNAME"@"$1"

# generate the script we want to run on the remote machine
echo "#!/bin/bash" >"$ADDSCRIPT"
echo "EXTINTERFACE=$(ip route get 8.8.8.8 | awk '{print $5}')" >>"$ADDSCRIPT"
cat ./k8smaker_config >>"$ADDSCRIPT"
cat ./k8smaker_precondition >>"$ADDSCRIPT"
echo "sudo usermod -aG docker $SSHUSERNAME" >>"$ADDSCRIPT"
echo "mkdir -p ~/.kube" >>"$ADDSCRIPT"
DISCOVERYTOKEN=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //')
CERTIFICATEKEY=$(sudo kubeadm init phase upload-certs --upload-certs | tail -1)
echo "sudo -i kubeadm join --config=/home/$SSHUSERNAME/k8smaker_addcontrolplane_$1_join.yaml" >>"$ADDSCRIPT"
echo "sudo docker run --network host --rm plndr/kube-vip:$KUBEVIPVERSION manifest pod --interface $EXTINTERFACE --vip $CONTROLPLANEVIP --controlplane --services --arp --leaderElection | tee kube-vip.yaml" >>"$ADDSCRIPT"
echo "sudo cp kube-vip.yaml /etc/kubernetes/manifests/kube-vip.yaml" >>"$ADDSCRIPT"
echo "sudo chmod 600 /etc/kubernetes/manifests/kube-vip.yaml" >>"$ADDSCRIPT"
chmod a+x "$ADDSCRIPT"

# Generate the kubeadm join script and copy it to the remote machine
cat >"$KUBEADMSCRIPT" <<EOF
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    token: ${BOOTSTRAPTOKEN}
    apiServerEndpoint: "${CONTROLPLANEENDPOINT}:6443"
    caCertHashes: ["sha256:${DISCOVERYTOKEN}"]
  timeout: 5m0s
  tlsBootstrapToken: ${BOOTSTRAPTOKEN}
controlPlane:
  localAPIEndpoint:
    advertiseAddress: ${NEWNODEIP}
    bindPort: 6443
  certificateKey: "${CERTIFICATEKEY}"
EOF

# copy the scripts to the new node and run it
scp -i "$HOME/.ssh/$CLUSTERNAME" "$ADDSCRIPT" "$SSHUSERNAME"@"$1":~/"k8smaker_addcontrolplane_$1"
scp -i "$HOME/.ssh/$CLUSTERNAME" "$KUBEADMSCRIPT" "$SSHUSERNAME"@"$1":~/"k8smaker_addcontrolplane_$1_join.yaml"
ssh -t -i "$HOME/.ssh/$CLUSTERNAME" "$SSHUSERNAME"@"$1" ~/"k8smaker_addcontrolplane_$1"

# Configure kubectl for each control-plane node
scp -i "$HOME/.ssh/$CLUSTERNAME" ~/.kube/config "$SSHUSERNAME"@"$1":~/.kube/config
