#!/bin/bash

# If you have an SSD device, declare it here and the script will make sure it's mounted
# whereever DATAFOLDER isi.  It's your job to make sure it's partitioned (use parted) and 
# formatted (use mkfs.ext4) first.  I don't do thisi for you, in case there's other stuff
# on the drive already.
SSD="/dev/nvme0n1"

# Even if you have no SSD, this is the root of where Docker and etcd data will live.
# You must specify this folder to be SOMEWHERE, as /docker and /etcd are mounted beneath it.
DATAFOLDER="/mnt/nvme"

# This script doesn't use a randomized bootstrap token, nor does it expire.  Slight security issue.
# Definitely change this, but it must be EXACTLY this many letters long.
BOOTSTRAPTOKEN="secret.bootstraptokenxx"

# To select your cluster, you do this: kubectl config use-context CLUSTERNAME
CLUSTERNAME="metalgods"

# Can be any subnet, but CLUSTERDNS needs to be on the SERVICESUBNET
SERVICESUBNET="10.99.0.0/16"
CLUSTERDNS="10.99.0.10"

# Can be any subnet, probably non-routable only.  Google up "non-routable ip addresses"
PODSUBNET="10.98.0.0/16"

# This is the username used when SSH'ing into machines
SSHUSERNAME="jhughes"

# Here you control whether you want control-node1 to also be a worker. 0 means no.
CONTROLISWORKER=1

# DO NOT PUT AN IP ADDRESS HERE!  You cannot change this value after creating the cluster.
# BareMetal: Leave it alone.  The name is added to the /etc/hosts on each node, which allows
# you to substitute a load balancer IP address on each node if you later need to.
# AWS: Put the actual name of your internal control plane load balancer here, if you plan
# to use one.  Otherwise leave it alone.  You can always come back and sub in the LB's IP address
# but those sometimes change without notice, so YMMV.
CONTROLPLANEENDPOINT="control-nodes"

# These let you control the versions of packages being installed.  I have no way to guarantee any
# combination will work except those I have checked in together (which means I tested them myself).
KUBERNETESVERSION="1.19.1"
ISTIOVERSION="1.7.1"
CALICOVERSION="v3.16.1"
