#!/bin/bash
# Do not run this directly!  Rather, any code you want to run on control AND worker nodes
# can be added here, as it runs before the cluster is initialized or before the worker joins.

if [[ $(whoami) == "root" ]]; then
   echo "Must not run as root."
   exit 1
fi

if [[ $SSD == '' ]]; then
   echo "Do not run this directly.  This is used by other scripts."
   exit 1;
fi

# Get onto a K8s and Docker version that will play nice together.
if command kubelet 2>/dev/null; then
   sudo systemctl stop kubelet
fi
sudo apt-mark unhold kubelet kubeadm kubectl
sudo apt-get purge -y kubelet kubeadm kubectl
sudo rm -rf /etc/kubernetes /var/lib/etcd /var/lib/kubelet
sudo apt-get update >/dev/null 2>&1
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common gnupg2 gnupg-agent
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update 
sudo apt-get install -y containerd.io=1.2.13-2 docker-ce=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) docker-ce-cli=5:19.03.11~3-0~ubuntu-$(lsb_release -cs)
sudo tee /etc/docker/daemon.json <<EOF >/dev/null
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
sudo mkdir -p /etc/systemd/system/docker.service.d

# Make sure $DATAFOLDER exists
sudo mkdir -p "$DATAFOLDER"
sudo mkdir -p "$DATAFOLDER"/docker
sudo mkdir -p "$DATAFOLDER"/etcd
sudo ln -s "$DATAFOLDER"/etcd /var/lib/etcd

# If there's a device at $SSD, we set it up to mount at the DATAFOLDER location.
if [[ -b "$SSD" ]]; then
   SSDUUID=$(lsblk "$SSD" -o UUID -n | tr '\n' ' ' | cut -c 2-37)
   echo "Found $SSD as $SSDUUID"

   if grep -q "$SSDUUID" /etc/fstab; then
      echo "Disk is already in /etc/fstab."
   else
      echo "UUID=$SSDUUID  $DATAFOLDER  ext4  defaults  0  2" | sudo tee -a /etc/fstab >/dev/null
      echo "Added $SSD to /etc/fstab"
   fi
   sudo mount "$DATAFOLDER"
fi

# Make sure that $DATAFOLDER/docker is where things are stored rather than /var/lib/docker 
SEDCMD="sed -i 's%^ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock.*$%ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -g $DATAFOLDER/docker%g' /lib/systemd/system/docker.service"
echo "Adding $DATAFOLDER to docker working folder"
eval "sudo $SEDCMD"

# add a DNS entry so we can do HA control node load balancing if we want to later.
if grep -q "$CONTROLNODEIP control-nodes" /etc/hosts; then
   echo "/etc/hosts already setup"
else
   echo "$CONTROLNODEIP control-nodes" | sudo tee -a /etc/hosts >/dev/null
   echo "Added $CONTROLNODEIP control-nodes entry to /etc/hosts"
fi

# Performance improves if you disable Transparent Huge Pages.
sudo apt-get install -y hugepages
sudo tee /etc/rc.local <<EOF >/dev/null
#!/bin/bash
hugeadm --thp-never
EOF
sudo chmod a+x /etc/rc.local
sudo hugeadm --thp-never

# Swapfile must be off to run k8s properly
sudo swapoff -a >/dev/null 2>&1 || true
sudo sed -i '/^\/swapfile/s/^/#/' /etc/fstab

# Configure prerequisites for Kubernetes
sudo tee /etc/sysctl.d/k8s.conf <<EOF >/dev/null
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo tee /etc/apt/sources.list.d/kubernetes.list <<EOF >/dev/null
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

# Check current versions available of these packages like this: apt-cache madison kubelet 
sudo apt-get update
sudo apt-get install -y kubelet=1.18.4-00 kubeadm=1.18.4-00 kubectl=1.18.4-00
sudo apt-mark hold kubelet kubeadm kubectl
sudo systemctl daemon-reload
sudo systemctl restart docker
sudo systemctl enable docker
sudo systemctl restart kubelet

# Add tab completion to bash for kubectl
kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl >/dev/null
